### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by bevacqua** [jsvine/waybackpack#10]
Hey there. Using `waybackpack` for [`shots`](https://github.com/bevacqua/shots) and loving it!

I think there should be a way to follow redirects, _at the very least as an option_. I'd enable it by default though.

**Comment by jsvine** [comment]
Thanks @bevacqua! I think enabling redirects as an option is a good idea. I'll plan on adding it to the next release. (Or, if you'd like, you can submit a pull request to the `develop` branch.)

Oh, and `shots` is great! So smart. 🎉

**Comment by jsvine** [comment]
v0.2.0, now on the `develop` branch, includes a `--follow-redirects` flag. Along the lines of what you were hoping?

If you want to test it, clone this repo, `git checkout develop`, and then `pip install -e .`

**Comment by jsvine** [comment]
Now in `master` and pushed to PyPi.
