### ISSUE TITLE
Wildcard url queries

### ISSUE THREAD

**Issue by fgregg** [jsvine/waybackpack#16]
Thanks for the great library.

I hacked up a way to download all the content prefixed by certain path. I.e. 

`http://www.oalj.dol.gov/PUBLIC/ARB/REFERENCES/CASELIST/*`

This is obviously related to #8, but it's not quite the same thing. I wanted to see if you would be interested in seeing a PR for this?

**Comment by jsvine** [comment]
Oooh, very interested in this! Many thanks in advance.

**Comment by fgregg** [comment]
Closed in favor of #17
