### ISSUE TITLE
Empty index.html with "found capture at xxxxxxxxxx"

### ISSUE THREAD

**Issue by tarekeldeeb** [jsvine/waybackpack#30]
All downloaded index.html files are have this single line:
found capture at xxxxxx

> $ waybackpack -d . www.masrawy.com
INFO:waybackpack.pack: Fetching www.masrawy.com @ 20000621155312
INFO:waybackpack.session: HTTP status code: 302
INFO:waybackpack.pack: Writing to ./20000621155312/www.masrawy.com/index.html

> INFO:waybackpack.pack: Fetching www.masrawy.com @ 20000711031156
INFO:waybackpack.session: HTTP status code: 302
INFO:waybackpack.pack: Writing to ./20000711031156/www.masrawy.com/index.html

> INFO:waybackpack.pack: Fetching www.masrawy.com @ 20001018073034
INFO:waybackpack.session: HTTP status code: 302
INFO:waybackpack.pack: Writing to ./20001018073034/www.masrawy.com/index.html

> INFO:waybackpack.pack: Fetching www.masrawy.com @ 20001109072800
INFO:waybackpack.session: HTTP status code: 302
INFO:waybackpack.pack: Writing to ./20001109072800/www.masrawy.com/index.html

**Comment by jsvine** [comment]
Does passing `--follow-redirects` on the command line improve the situation? ([HTTP status code 302](https://en.wikipedia.org/wiki/HTTP_302) is a URL redirect.)

**Comment by tarekeldeeb** [comment]
This fixed the issue.
Thanks.
