### ISSUE TITLE
Is there a way to limit the downloads to just zip files?

### ISSUE THREAD

**Issue by BGMcoder** [jsvine/waybackpack#34]
There is a site I want to download, but I don't want any of the site pages - just the zip files therein.  Is there a way to limit the results?

It seems like the script only downloads the index.html pages.  I'm looking for site/*/*/*.zip

**Comment by jsvine** [comment]
No, but I believe you should be able to get what you want by querying the Wayback Machine's CDX endpoint directly: https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server#url-match-scope
