### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by CuloArdido** [jsvine/waybackpack#35]
The question is why there have been no updates for more than 3 years, besides when trying to download a site just download an empty index.html.
As a replacement I found [wayback-machine-scraper](https://github.com/sangaline/wayback-machine-scraper) although it seems that it only downloads the html forgetting the images or CSS. There are also other projects about Wayback Machine in [this topic](https://github.com/topics/wayback-machine) but only a few are for saving snapshots.

**Comment by jsvine** [comment]
Hi @CuloArdido, this project is currently stable. If you see a specific bug, however, please do file an issue for it, detailing the steps you took and what seems not to be working.

In the future, I might try implementing more features (e.g. wildcard searching, similar to what is proposed [here](https://github.com/jsvine/waybackpack/pull/17)), but there's no guarantee.
