### ISSUE TITLE
Syntax error in Collab and Jupyter?

### ISSUE THREAD

**Issue by ppival** [jsvine/waybackpack#45]
Attempting to run in either [Google Colab](https://colab.research.google.com/) or a Jupyter notebook. It installs, but returns a syntax error with any URL:

`  File "<ipython-input-10-e826c76cce5b>", line 1
    waybackpack dol.gov -d ~/Downloads/dol-wayback --to-date 2020
                  ^
SyntaxError: invalid syntax`

**Comment by jsvine** [comment]
It appears that you are running `waybackpack dol.gov -d ~/Downloads/dol-wayback --to-date 2020` as Python code, which it is not; instead, it's a shell command. Instead, if you want to execute the command in a Jupyter notebook, try using the `%%bash` "magic" in the relevant notebook cell:

```
%%bash
waybackpack dol.gov -d ~/Downloads/dol-wayback --to-date 2020
```

**Comment by ppival** [comment]
Thanks, @jsvine that of course did the trick :-) I still have to figure out files with Colab, but it worked perfectly in Jupyter. Bookmarking [Magics](https://ipython.readthedocs.io/en/stable/interactive/magics.html)

Much appreciated!
