### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by jwilk** [jsvine/waybackpack#73]
README and `setup.py` claim that Python 2 is supported, but 27abd9de4b9394cf9444702be5cc0efce687e3ee ("Reformat with psf/black") added `rb"…"` strings, which is a Python 3.3+ syntax.

(I don't have any personal interest in running waybackpack under Python 2.)

**Comment by jsvine** [comment]
Good catch, and thanks! I should have updated that a while ago. Now done here: https://github.com/jsvine/waybackpack/commit/febb1c2073a8f4d1d72b3e59ddcf2c0cfe72757d
