### ISSUE TITLE
KeyError when --uniques-only flag is specified

### ISSUE THREAD

**Issue by CaptSolo** [jsvine/waybackpack#81]
Program fails with KeyError when the `--uniques-only` flag is specified:

```
../waybackpack/cdx.py", line 46, in <listcomp>
    return [s for s in snapshots if int(s["dupecount"]) == 0]
KeyError: 'dupecount'
```

It looks like archive.org is not sending back the `dupecount` field even though the `'showDupeCount': 'true'` parameter gets sent along with the request.

**Comment by jsvine** [comment]
Thanks for flagging, @CaptSolo! Have now [pushed a change](https://github.com/jsvine/waybackpack/commit/9e896adfcdbd0bdcbe3a26f6f623273c81a58848) (available in v0.6.4) that provides a more informative error, although hopefully the API fixes the underlying problem (to render this moot).
